P_U3/Controllers/CitaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using P_U3.Context;
using P_U3.Models;

namespace P_U3.Controllers;

[Authorize]
public class CitaController : Controller
{
    private readonly BddCitasMedicasContext _context;

    public CitaController(BddCitasMedicasContext context)
    {
        _context = context;
    }

    // GET: Citas
    public async Task<IActionResult> Index()
    {
        var asdContext = _context.Cita
            .Include(c => c.Doctor)
            .Include(c => c.Paciente);
        return View(await asdContext.ToListAsync());
    }

    // GET: Citas/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return NotFound();


        var cita = await _context.Cita
            .Include(c => c.Doctor)
            .Include(c => c.Paciente)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (cita == null)
            return NotFound();


        return View(cita);
    }

    // GET: Citas/Create
    public IActionResult Create()
    {
        ViewData["DoctorId"] = new SelectList(_context.Set<Doctor>(), "Id", "Apellido");
        ViewData["PacienteId"] = new SelectList(_context.Set<Paciente>(), "Id", "Apellido");
        return View();
    }

    // POST: Citas/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Fecha,HoraDeInicio,Horas,DoctorId,PacienteId")] Cita cita)
    {
        var fechaActual = DateTime.Now;
        var fechaCita = cita.Fecha.ToDateTime(cita.HoraDeInicio);

        if (fechaCita < fechaActual)
            ModelState.AddModelError("Fecha", "La fecha de la cita no puede ser menor a la fecha actual");

        var fechasUsadas = await _context.Cita
            .Where(c => c.DoctorId == cita.DoctorId)
            .Where(c => c.Fecha == cita.Fecha)
            .Where(c => c.HoraDeInicio <= cita.HoraDeInicio.AddHours(cita.Horas) && cita.HoraDeInicio >= c.HoraDeInicio)
            .ToListAsync();

        if (fechasUsadas.Count > 0)
            ModelState.AddModelError("Fecha", "El doctor ya tiene una cita en ese horario");

        if (ModelState.IsValid)
        {
            _context.Add(cita);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        ViewData["DoctorId"] = new SelectList(_context.Set<Doctor>(), "Id", "Apellido", cita.DoctorId);
        ViewData["PacienteId"] = new SelectList(_context.Set<Paciente>(), "Id", "Apellido", cita.PacienteId);
        return View(cita);
    }

    // GET: Citas/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
            return NotFound();


        var cita = await _context.Cita.FindAsync(id);
        if (cita == null)
            return NotFound();

        ViewData["DoctorId"] = new SelectList(_context.Set<Doctor>(), "Id", "Apellido", cita.DoctorId);
        ViewData["PacienteId"] = new SelectList(_context.Set<Paciente>(), "Id", "Apellido", cita.PacienteId);
        return View(cita);
    }

    // POST: Citas/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id,
        [Bind("Id,Fecha,HoraDeInicio,Horas,DoctorId,PacienteId")]
        Cita cita)
    {
        if (id != cita.Id)
            return NotFound();
        
        var fechaActual = DateTime.Now;
        var fechaCita = cita.Fecha.ToDateTime(cita.HoraDeInicio);

        if (fechaCita < fechaActual)
            ModelState.AddModelError("Fecha", "La fecha de la cita no puede ser menor a la fecha actual");

        var fechasUsadas = await _context.Cita
            .Where(c => c.Id != cita.Id)
            .Where(c => c.DoctorId == cita.DoctorId)
            .Where(c => c.Fecha == cita.Fecha)
            .Where(c => c.HoraDeInicio <= cita.HoraDeInicio.AddHours(cita.Horas) && cita.HoraDeInicio >= c.HoraDeInicio)
            .ToListAsync();

        if (fechasUsadas.Count > 0)
            ModelState.AddModelError("Fecha", "El doctor ya tiene una cita en ese horario");
        
        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(cita);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CitaExists(cita.Id))
                    return NotFound();
                throw;
            }
            return RedirectToAction(nameof(Index));
        }

        ViewData["DoctorId"] = new SelectList(_context.Set<Doctor>(), "Id", "Apellido", cita.DoctorId);
        ViewData["PacienteId"] = new SelectList(_context.Set<Paciente>(), "Id", "Apellido", cita.PacienteId);
        return View(cita);
    }

    // GET: Citas/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
            return NotFound();


        var cita = await _context.Cita
            .Include(c => c.Doctor)
            .Include(c => c.Paciente)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (cita == null)
            return NotFound();


        return View(cita);
    }

    // POST: Citas/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var cita = await _context.Cita.FindAsync(id);
        if (cita != null)
            _context.Cita.Remove(cita);


        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool CitaExists(int id)
    {
        return _context.Cita.Any(e => e.Id == id);
    }
}

P_U3/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using P_U3.Context;
using P_U3.Models;

namespace P_U3.Controllers;

[Authorize]
public class DoctorController : Controller
{
    private readonly BddCitasMedicasContext _context;

    public DoctorController(BddCitasMedicasContext context)
    {
        _context = context;
    }

    // GET: Doctor
    public async Task<IActionResult> Index()
    {
        var asdContext = _context.Doctor.Include(d => d.Especialidad);
        return View(await asdContext.ToListAsync());
    }

    // GET: Doctor/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var doctor = await _context.Doctor
            .Include(d => d.Especialidad)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (doctor == null)
        {
            return NotFound();
        }

        return View(doctor);
    }

    // GET: Doctor/Create
    public IActionResult Create()
    {
        ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Nombre");
        return View();
    }

    // POST: Doctor/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Cedula,EspecialidadId")] Doctor doctor)
    {
        if (ModelState.IsValid)
        {
            _context.Add(doctor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        foreach (var error in ModelState.Values.SelectMany(modelState => modelState.Errors))
        {
            Console.WriteLine(error.ErrorMessage);
        }

        ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Nombre", doctor.EspecialidadId);
        return View(doctor);
    }

    // GET: Doctor/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var doctor = await _context.Doctor.FindAsync(id);
        if (doctor == null)
        {
            return NotFound();
        }
        ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Nombre", doctor.EspecialidadId);
        return View(doctor);
    }

    // POST: Doctor/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Cedula,EspecialidadId")] Doctor doctor)
    {
        if (id != doctor.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(doctor);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DoctorExists(doctor.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["EspecialidadId"] = new SelectList(_context.Especialidad, "Id", "Nombre", doctor.EspecialidadId);
        return View(doctor);
    }

    // GET: Doctor/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var doctor = await _context.Doctor
            .Include(d => d.Especialidad)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (doctor == null)
        {
            return NotFound();
        }

        return View(doctor);
    }

    // POST: Doctor/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var doctor = await _context.Doctor.FindAsync(id);
        if (doctor != null)
        {
            _context.Doctor.Remove(doctor);
        }
            
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool DoctorExists(int id)
    {
        return _context.Doctor.Any(e => e.Id == id);
    }
}

P_U3/Controllers/PacienteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using P_U3.Context;
using P_U3.Models;

namespace P_U3.Controllers;

[Authorize]
public class PacienteController : Controller
{
    private readonly BddCitasMedicasContext _context;

    public PacienteController(BddCitasMedicasContext context)
    {
        _context = context;
    }

    // GET: Pacientes
    public async Task<IActionResult> Index()
    {
        return View(await _context.Paciente.ToListAsync());
    }

    // GET: Pacientes/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var paciente = await _context.Paciente
            .FirstOrDefaultAsync(m => m.Id == id);
        if (paciente == null)
        {
            return NotFound();
        }

        return View(paciente);
    }

    // GET: Pacientes/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Pacientes/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,FechaDeNacimiento,Direccion,FechaDeRegistro")] Paciente paciente)
    {
        if (ModelState.IsValid)
        {
            _context.Add(paciente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(paciente);
    }

    // GET: Pacientes/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var paciente = await _context.Paciente.FindAsync(id);
        if (paciente == null)
        {
            return NotFound();
        }
        return View(paciente);
    }

    // POST: Pacientes/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,FechaDeNacimiento,Direccion,FechaDeRegistro")] Paciente paciente)
    {
        if (id != paciente.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(paciente);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PacienteExists(paciente.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(paciente);
    }

    // GET: Pacientes/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var paciente = await _context.Paciente
            .FirstOrDefaultAsync(m => m.Id == id);
        if (paciente == null)
        {
            return NotFound();
        }

        return View(paciente);
    }

    // POST: Pacientes/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var paciente = await _context.Paciente.FindAsync(id);
        if (paciente != null)
        {
            _context.Paciente.Remove(paciente);
        }
            
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool PacienteExists(int id)
    {
        return _context.Paciente.Any(e => e.Id == id);
    }
}

P_U3/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using P_U3.Context;
using P_U3.Models;

namespace P_U3.Controllers;

[Authorize]
public class UsuarioController : Controller
{
    private readonly BddCitasMedicasContext _context;

    public UsuarioController(BddCitasMedicasContext context)
    {
        _context = context;
    }

    // GET: Usuario
    public async Task<IActionResult> Index()
    {
        return View(await _context.Usuario.ToListAsync());
    }

    // GET: Usuario/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return NotFound();
        

        var usuario = await _context.Usuario
            .FirstOrDefaultAsync(m => m.Id == id);
        if (usuario == null)
            return NotFound();
        

        return View(usuario);
    }

    // GET: Usuario/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Usuario/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Email,Contrasenia")] Usuario usuario)
    {
        if (!ModelState.IsValid) return View(usuario);
        _context.Add(usuario);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    // GET: Usuario/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
            return NotFound();


        var usuario = await _context.Usuario.FindAsync(id);
        if (usuario == null)
            return NotFound();

        return View(usuario);
    }

    // POST: Usuario/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Email,Contrasenia")] Usuario usuario)
    {
        if (id != usuario.Id)
            return NotFound();
        

        if (!ModelState.IsValid) return View(usuario);
        try
        {
            _context.Update(usuario);
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!UsuarioExists(usuario.Id))
                return NotFound();

            throw;
        }

        return RedirectToAction(nameof(Index));
    }

    // GET: Usuario/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
            return NotFound();
        
        var usuario = await _context.Usuario
            .FirstOrDefaultAsync(m => m.Id == id);
        if (usuario == null)
            return NotFound();
        
        return View(usuario);
    }

    // POST: Usuario/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var usuario = await _context.Usuario.FindAsync(id);
        if (usuario != null)
            _context.Usuario.Remove(usuario);
        
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool UsuarioExists(int id)
    {
        return _context.Usuario.Any(e => e.Id == id);
    }
}

P_U3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] -SCM - Sistema de Citas Médicas &copy; 2023</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <script src="https://kit.fontawesome.com/c903d303d4.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@6.1.8/index.global.min.js"></script>

</head>
<body class="d-flex min-vh-100 h-100">
<aside class="d-flex flex-column flex-shrink-0 p-3 text-white bg-success"
       style="
            width: 280px;
            border-right: rgba(173,181,189,0.3) 1px solid;
            position: fixed;
            height: 100%;
       ">

    <a asp-controller="Home" asp-action="Index" class="d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto text-decoration-none text-white">
        <div class="mx-2 fs-2">
            <i class="fa-solid fa-hospital"></i>
        </div>
        <span class="fs-1 fw-bold">SCM</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a asp-controller="Home" asp-action="Index" class="nav-link text-white">
                <i class="fa-solid fa-house"></i>
                Inicio
            </a>
        </li>
        <li>
            <a asp-controller="Cita" asp-action="Index" class="nav-link text-white">
                <i class="fa-solid fa-calendar"></i>
                Citas
            </a>
        </li>
        <li>
            <a asp-controller="Paciente" asp-action="Index" class="nav-link text-white">
                <i class="fa-solid fa-user"></i>
                Pacientes
            </a>
        </li>
        <li>
            <a asp-controller="Doctor" asp-action="Index" class="nav-link text-white">
                <i class="fa-solid fa-user-md"></i>
                Doctores
            </a>
        </li>
        <li>
            <a asp-controller="Usuario" asp-action="Index" class="nav-link text-white">
                <i class="fa-solid fa-user"></i>
                Usuarios
            </a>
        </li>
        <li>
            <a asp-controller="Especialidad" asp-action="Index" class="nav-link text-white">
                <i class="fa-solid fa-user-md"></i>
                Especialidades
            </a>
        </li>
    </ul>
    <hr>
    <div class="dropdown">
        <a href="#"
           class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
           id="dropdownUser1"
           data-bs-toggle="dropdown"
           aria-expanded="false">
            <strong>
                Invitado
            </strong>
        </a>
        <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser1">
            <li>
                <a class="dropdown-item" href="#">Ajustes</a>
            </li>
            <li>
                <a class="dropdown-item" href="#">Perfil</a>
            </li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li>
                @if (User.Identity is { IsAuthenticated: true })
                {
                    <form class="dropdown-item d-flex align-items-center" method="post" asp-action="Logout" asp-controller="Access">
                         <i class="fa-solid fa-arrow-right-from-bracket"></i>
                        <button type="submit" class="dropdown-item">Cerrar Sesión</button>
                    </form>
                }
                else
                {
                    <a class="dropdown-item d-flex align-items-center" asp-action="Login" asp-controller="Access">
                        <i class="fa-solid fa-right-to-bracket"></i>
                        Iniciar Sesión
                    </a>
                }
            </li>
        </ul>
    </div>
</aside>

<main class="container-fluid" style="width: calc(100% - 280px); margin-left: 280px">
    <div class="row mt-3">
        <div class="col d-flex justify-content-center">
            <h1 class="fw-bold">Sistema de Citas Médicas</h1>
        </div>
        <hr>
    </div>
    <div>
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SCM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
</main>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
<script>
const currentUrl = window.location.href;
const navLinks = document.querySelectorAll('.nav-link');
navLinks.forEach(function(navLink) {
  if (navLink.href === currentUrl) {
    navLink.classList.add('active');
  }
});
</script>
</body>
</html>